// Add future projects to the projects array. Each field supports Chinese and English.
window.siteContent = {
  copy: {
    zh: {skip:'跳至内容',navAbout:'关于',navResearch:'研究',navExperience:'经历',navProjects:'项目',heroRole:'计算数学博士 · 量化研究员',heroSummary:'从数据中发现规律，用数学理解复杂系统。我的研究与实践连接科学计算、量化金融和人工智能。',explore:'探索项目',getInTouch:'与我联系',affiliation:'量化研究 & AI',visualCaption:'从观测数据到可解释的模型',data:'数据',models:'模型',structure:'结构',visualFoot:'数学提供结构，数据带来洞察。',aboutTitle:'在数学与现实问题之间。',aboutText:'我于 2026 年从香港浸会大学博士毕业，研究方向为计算数学。现在在 AQUMON 担任量化研究员，同时从事 AI 相关研究。',aboutText2:'我的学术研究聚焦从含噪数据中识别偏微分方程，结合弱形式、稀疏优化和机器学习构建可解释的模型。在实践中，我也探索 AI 智能体、金融数据分析与量化研究工具。',researchTitle:'我关注的问题',researchIntro:'让数据、模型与领域知识相互连接。',publicationsTitle:'精选论文',publicationsNote:'弱形式 · 稀疏回归 · 科学计算',experienceTitle:'从学术到实践',experienceIntro:'跨越数学、数据科学与金融的学习和工作经历。',workTitle:'工作经历',educationTitle:'教育经历',tools:'常用工具',projectsTitle:'研究与项目',projectsIntro:'一些已经开展的探索，更多工作将在这里陆续分享。',futureTitle:'探索仍在继续',futureText:'这里会继续记录我的研究、工具与个人项目。',contactTitle:'让想法开始交流。',contactText:'欢迎交流科学计算、量化研究、AI 和有趣的项目。',footer:'数学 · 研究 · 实践',backTop:'回到顶部',paper:'阅读论文',code:'查看代码',demo:'查看演示',research:'学术研究',applied:'应用研究',description:'Cheng Tang 的个人主页。香港浸会大学计算数学博士，AQUMON 量化研究员，关注数据驱动的科学计算、量化研究与 AI。'},
    en: {skip:'Skip to content',navAbout:'About',navResearch:'Research',navExperience:'Journey',navProjects:'Projects',heroRole:'PhD in Computational Mathematics · Quantitative Researcher',heroSummary:'Finding patterns in data and understanding complex systems through mathematics. My work connects scientific computing, quantitative finance, and artificial intelligence.',explore:'Explore my work',getInTouch:'Get in touch',affiliation:'Quantitative Research & AI',visualCaption:'From observations to interpretable models',data:'Data',models:'Models',structure:'Structure',visualFoot:'Structure through mathematics. Insight through data.',aboutTitle:'Between mathematics and real-world problems.',aboutText:'I completed my PhD at Hong Kong Baptist University in 2026, with a focus on computational mathematics. I am now a Quantitative Researcher at AQUMON, where I also work on AI research.',aboutText2:'My academic research focuses on identifying partial differential equations from noisy data, combining weak formulations, sparse optimization, and machine learning to build interpretable models. In practice, I also explore AI agents, financial data analysis, and tools for quantitative research.',researchTitle:'Questions I explore',researchIntro:'Connecting data, mathematical models, and domain knowledge.',publicationsTitle:'Selected publications',publicationsNote:'Weak formulations · Sparse regression · Scientific computing',experienceTitle:'From research to practice',experienceIntro:'A journey through mathematics, data science, and finance.',workTitle:'Experience',educationTitle:'Education',tools:'Tools I work with',projectsTitle:'Research & projects',projectsIntro:'Selected explorations so far. More work will be shared here over time.',futureTitle:'The exploration continues',futureText:'A growing collection of research, tools, and personal projects.',contactTitle:'Let’s exchange ideas.',contactText:'Open to conversations about scientific computing, quantitative research, AI, and interesting projects.',footer:'Mathematics · Research · Practice',backTop:'Back to top',paper:'Read paper',code:'View code',demo:'View demo',research:'RESEARCH',applied:'APPLIED RESEARCH',description:'Cheng Tang — PhD in computational mathematics from Hong Kong Baptist University and Quantitative Researcher at AQUMON. Scientific computing, quantitative research, and AI.'}
  },
  research: [
    {title:{zh:'数据驱动的科学计算',en:'Data-driven scientific computing'},text:{zh:'从含噪的时空观测中发现控制方程，研究弱形式方法、变系数 PDE 识别与稀疏模型选择。',en:'Discovering governing equations from noisy spatiotemporal observations using weak formulations, variable-coefficient PDE identification, and sparse model selection.'},tag:'PDE IDENTIFICATION / SPARSE OPTIMIZATION'},
    {title:{zh:'机器学习与 AI',en:'Machine learning & AI'},text:{zh:'探索神经网络在科学问题中的应用，以及 AI 智能体、RAG 和自然语言处理在金融研究中的实践。',en:'Exploring neural networks for scientific problems, alongside AI agents, retrieval-augmented generation, and natural language processing for financial research.'},tag:'NEURAL NETWORKS / AGENTIC AI'},
    {title:{zh:'量化研究与金融数据',en:'Quantitative research'},text:{zh:'把数学建模与数据工程连接起来，关注市场数据分析、情绪信号、链上风险和研究工具的构建。',en:'Connecting mathematical modeling with data engineering through market analytics, sentiment signals, on-chain risk analysis, and research tooling.'},tag:'FINANCIAL DATA / QUANTITATIVE METHODS'}
  ],
  publications: [
    {year:'2026',title:'WG-IDENT: Weak Group Identification of PDEs with Varying Coefficients',authors:'Cheng Tang, Roy Y. He, Hao Liu',venue:{zh:'Journal of Computational Physics · 已发表',en:'Journal of Computational Physics · Published'},url:'https://www.sciencedirect.com/science/article/pii/S0021999125007363'},
    {year:'2026',title:'PriorIDENT: Prior-Informed PDE Identification from Noisy Data',authors:'Cheng Tang, Hao Liu, Dong Wang',venue:{zh:'arXiv:2603.05946 · 预印本',en:'arXiv:2603.05946 · Preprint'},url:'https://arxiv.org/abs/2603.05946'}
  ],
  work: [
    {date:{zh:'目前',en:'Current'},name:'AQUMON',role:{zh:'量化研究员',en:'Quantitative Researcher'},detail:{zh:'从事量化研究与 AI 相关研究工作。',en:'Working on quantitative research and AI-related research.'}},
    {date:{zh:'2025.07 — 2026.01',en:'Jul 2025 — Jan 2026'},name:'AQUMON',role:{zh:'量化研究实习生',en:'Quantitative Research Intern'},detail:{zh:'开发 Crypto Alpha Terminal，探索 AI 智能体、情绪分析与链上风险建模。',en:'Developed Crypto Alpha Terminal, exploring AI agents, sentiment analysis, and on-chain risk models.'}},
    {date:{zh:'2025.06 — 2025.07',en:'Jun — Jul 2025'},name:'Verified Metrics',role:{zh:'AI 产品实习生',en:'AI Product Intern'},detail:{zh:'构建金融文档 RAG 工作流，参与 AI 估值助手的开发。',en:'Built RAG workflows for financial documents and contributed to an AI valuation assistant.'}},
    {date:{zh:'2021.03 — 2021.05',en:'Mar — May 2021'},name:{zh:'华安证券',en:'HuaAn Securities'},role:{zh:'金融工程实习生',en:'Financial Engineering Intern'},detail:{zh:'开发量化分析平台，开展市场数据分析与研究报告工作。',en:'Developed a quantitative analytics platform and worked on market analysis and research reporting.'}}
  ],
  education: [
    {date:'2022 — 2026',name:{zh:'香港浸会大学',en:'Hong Kong Baptist University'},role:{zh:'博士 · 计算数学研究',en:'PhD · Computational Mathematics Research'},detail:{zh:'聚焦 PDE 识别、数据驱动问题与机器学习；担任研究生代表及数学课程助教。',en:'Focused on PDE identification, data-driven problems, and machine learning; served as a research postgraduate representative and mathematics teaching assistant.'}},
    {date:{zh:'2025.03 — 2025.06',en:'Mar — Jun 2025'},name:{zh:'佐治亚理工学院',en:'Georgia Institute of Technology'},role:{zh:'数学系访问博士生',en:'Visiting PhD Student · Mathematics'},detail:{zh:'与 Sung Ha Kang 和 Wenjing Liao 教授开展神经网络与 PDE 识别研究。',en:'Worked with Professors Sung Ha Kang and Wenjing Liao on neural networks and PDE identification.'}},
    {date:'2021 — 2022',name:{zh:'杜克大学',en:'Duke University'},role:{zh:'量化管理硕士 · 商业分析，金融方向',en:'MS in Quantitative Management · Business Analytics, Finance Track'},detail:{zh:'数据科学、决策建模、数据可视化与衍生品。',en:'Data science, decision modeling, data visualization, and derivatives.'}},
    {date:'2016 — 2020',name:{zh:'加州大学圣芭芭拉分校',en:'University of California, Santa Barbara'},role:{zh:'数学科学学士 · 辅修物理',en:'BS in Mathematical Science · Minor in Physics'},detail:{zh:'数值分析、实分析、高等线性代数与物理。',en:'Numerical analysis, real analysis, advanced linear algebra, and physics.'}}
  ],
  projects: [
    {title:'WG-IDENT',type:'research',subtitle:{zh:'变系数偏微分方程识别',en:'Identifying PDEs with varying coefficients'},text:{zh:'以弱形式和组稀疏回归从含噪数据中识别变系数 PDE。结合 B 样条、谱分析与特征剪枝，提高模型选择的稳定性。',en:'A weak-form, group-sparse framework for discovering variable-coefficient PDEs from noisy data. B-splines, spectral analysis, and feature trimming support stable model selection.'},tags:['Scientific Computing','Sparse Regression','B-splines'],links:[{label:'paper',url:'https://www.sciencedirect.com/science/article/pii/S0021999125007363'},{label:'code',url:'https://github.com/ChengTang1205/WG_IDENT_demo'}]},
    {title:'PriorIDENT',type:'research',subtitle:{zh:'融合先验知识的方程发现',en:'Equation discovery with physical priors'},text:{zh:'将物理先验融入候选模型与弱形式稀疏回归，使从含噪数据中发现的方程保留物理结构与可解释性。',en:'Integrating physical priors into candidate models and weak-form sparse regression to discover interpretable equations that preserve physical structure in noisy data.'},tags:['Physics-informed','PDE Discovery','Optimization'],links:[{label:'paper',url:'https://arxiv.org/abs/2603.05946'}]},
    {title:'Crypto Alpha Terminal',type:'applied',subtitle:{zh:'量化数据与 AI 研究工具',en:'Quantitative data & AI research tools'},text:{zh:'整合市场与链上数据的量化分析平台，包含 AI 智能体研究工作流、情绪分析和风险监测。',en:'A quantitative analytics platform integrating market and on-chain data, with AI-agent research workflows, sentiment analysis, and risk monitoring.'},tags:['Python','Next.js','LangGraph'],links:[{label:'demo',url:'https://crypto-alpha-terminal-p8iyc6dqfq2rbpvaxczwlr.streamlit.app/'}]},
    {title:{zh:'数据驱动的最优测试函数',en:'Data-driven optimal test functions'},type:'research',subtitle:{zh:'系统识别与噪声抑制',en:'System identification & noise suppression'},text:{zh:'通过频谱分析从数据中自适应构建 B 样条测试函数，在保留有效信息的同时抑制微分过程中的噪声放大。',en:'Learning adaptive B-spline test functions from spectral analysis to retain useful information while suppressing noise amplification in differentiation.'},tags:['Signal Processing','FFT','System Identification'],links:[]}
  ]
};
